### ISSUE TITLE
correct that this only parses microdata instead of rdfA and JSON-ld options?

### ISSUE THREAD

**Issue by gebrits** [vespa/semantic-schema-parser#6]
Just to be sure I'm not missing anything, is it correct that this library only parses microdata instead of rdfA and JSON-LD options of formatting schema.org?

**Comment by vespa** [comment]
Hey. 

Yes, it is. This lib was created before the introduction of JSON-LD and, at that time, schema was kind of an alternative to RDFa (if you google it, would find articles like 'RDFa vs Schema', mostly of 2011-2012, I believe). 

There's a long time I intent to create a new project to cover other microdata formats. Unfortunatelly, I didn't had the time to do it properly.
